media:
  input: media
  output: /media
  rename: safe
  categories:
    - image
  extensions:
    - jpg
    - jpeg
    - png
    - webp

content:
  - name: projects
    label: Proyectos
    type: file
    path: content/proyectos.json
    format: json
    list: true
    fields:
      - name: title
        label: Título
        type: string
        required: true
      - name: category
        label: Categoría
        type: string
        required: true
      - name: description
        label: Descripción
        type: text
      - name: image
        label: Imagen principal
        type: image
        options:
          path: proyectos
          extensions:
            - jpg
            - jpeg
            - png
            - webp
      - name: alt
        label: Texto alternativo
        type: string
      - name: visible
        label: Mostrar en la web
        type: boolean